// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoomApi.Infrastructure.Data;

#nullable disable

namespace RoomApi.Infrastructure.Data.Migrations
{
    [DbContext(typeof(RoomDbContext))]
    partial class RoomDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoomApi.Domain.Entities.AgreeableBreed", b =>
                {
                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BreedId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoomId", "BreedId");

                    b.ToTable("AgreeableBreeds");

                    b.HasData(
                        new
                        {
                            RoomId = new Guid("bd0d3a46-dfd5-4a76-bd29-dd5aec099207"),
                            BreedId = new Guid("aaae8a7b-abd1-4169-0383-08dd6a9d0b8b")
                        },
                        new
                        {
                            RoomId = new Guid("442a2f8f-d71d-4426-99bd-091799147c7c"),
                            BreedId = new Guid("aaae8a7b-abd1-4169-0383-08dd6a9d0b8b")
                        },
                        new
                        {
                            RoomId = new Guid("442a2f8f-d71d-4426-99bd-091799147c7c"),
                            BreedId = new Guid("f5614fe7-b506-4379-d3fa-08dd53047a20")
                        },
                        new
                        {
                            RoomId = new Guid("c8c2fec0-924e-42cf-95e1-5a56c74566ac"),
                            BreedId = new Guid("aaae8a7b-abd1-4169-0383-08dd6a9d0b8b")
                        },
                        new
                        {
                            RoomId = new Guid("c8c2fec0-924e-42cf-95e1-5a56c74566ac"),
                            BreedId = new Guid("f5614fe7-b506-4379-d3fa-08dd53047a20")
                        });
                });

            modelBuilder.Entity("RoomApi.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomDesc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoomId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = new Guid("9cbe5159-058d-4021-95f0-66a3deb96226"),
                            IsVisible = true,
                            PricePerDay = 300000m,
                            PricePerHour = 50000m,
                            RoomDesc = "Phòng nhỏ, phù hợp chó con",
                            RoomName = "Phòng 101",
                            RoomTypeId = new Guid("9115f1c9-5d04-4199-9ba1-b507d5b14866")
                        },
                        new
                        {
                            RoomId = new Guid("bd0d3a46-dfd5-4a76-bd29-dd5aec099207"),
                            IsVisible = true,
                            PricePerDay = 500000m,
                            PricePerHour = 80000m,
                            RoomDesc = "Phòng VIP cho mèo quý tộc",
                            RoomName = "Phòng 202",
                            RoomTypeId = new Guid("25f4b852-e34e-435d-88f9-7207e8d00149")
                        },
                        new
                        {
                            RoomId = new Guid("442a2f8f-d71d-4426-99bd-091799147c7c"),
                            IsVisible = true,
                            PricePerDay = 450000m,
                            PricePerHour = 70000m,
                            RoomDesc = "Phòng gia đình, cho mèo",
                            RoomName = "Phòng 303",
                            RoomTypeId = new Guid("0c391bbe-fff6-4578-ba12-ab3497927553")
                        },
                        new
                        {
                            RoomId = new Guid("c8c2fec0-924e-42cf-95e1-5a56c74566ac"),
                            IsVisible = true,
                            PricePerDay = 600000m,
                            PricePerHour = 90000m,
                            RoomDesc = "Phòng nhỏ cho mèo",
                            RoomName = "Phòng 404",
                            RoomTypeId = new Guid("9115f1c9-5d04-4199-9ba1-b507d5b14866")
                        });
                });

            modelBuilder.Entity("RoomApi.Domain.Entities.RoomAccessory", b =>
                {
                    b.Property<Guid>("RoomAccessoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("RoomAccessoryDesc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RoomAccessoryImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomAccessoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoomAccessoryId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("RoomAccessories");

                    b.HasData(
                        new
                        {
                            RoomAccessoryId = new Guid("992ff21f-ab7f-47c8-9477-ba3a5c5dc10b"),
                            IsVisible = true,
                            RoomAccessoryDesc = "Khay vệ sinh cho mèo",
                            RoomAccessoryImagePath = "khaycat.jpg",
                            RoomAccessoryName = "Khay cát",
                            RoomTypeId = new Guid("0c391bbe-fff6-4578-ba12-ab3497927553"),
                            ServiceId = new Guid("4709e073-15e2-46a6-90a4-4a89f19b6415")
                        },
                        new
                        {
                            RoomAccessoryId = new Guid("41fe86ff-efa4-4686-938c-3060e74206bc"),
                            IsVisible = true,
                            RoomAccessoryDesc = "Cho mèo chơi và tập thể dục",
                            RoomAccessoryImagePath = "cayleo.jpg",
                            RoomAccessoryName = "Cây leo",
                            RoomTypeId = new Guid("25f4b852-e34e-435d-88f9-7207e8d00149"),
                            ServiceId = new Guid("280dad45-5bcf-4ff8-942b-43407af1b8d1")
                        },
                        new
                        {
                            RoomAccessoryId = new Guid("6050f700-f906-4366-b140-be301d6f2d15"),
                            IsVisible = true,
                            RoomAccessoryDesc = "Quan sát thú cưng từ xa",
                            RoomAccessoryImagePath = "camera.jpg",
                            RoomAccessoryName = "Camera",
                            RoomTypeId = new Guid("25f4b852-e34e-435d-88f9-7207e8d00149"),
                            ServiceId = new Guid("7fae2056-1267-4372-b59c-d40287de8aad")
                        });
                });

            modelBuilder.Entity("RoomApi.Domain.Entities.RoomImage", b =>
                {
                    b.Property<string>("RoomImagePath")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoomImagePath");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomImages");

                    b.HasData(
                        new
                        {
                            RoomImagePath = "101.jpg",
                            RoomId = new Guid("9cbe5159-058d-4021-95f0-66a3deb96226")
                        },
                        new
                        {
                            RoomImagePath = "202.jpg",
                            RoomId = new Guid("bd0d3a46-dfd5-4a76-bd29-dd5aec099207")
                        },
                        new
                        {
                            RoomImagePath = "303.jpg",
                            RoomId = new Guid("442a2f8f-d71d-4426-99bd-091799147c7c")
                        },
                        new
                        {
                            RoomImagePath = "404.jpg",
                            RoomId = new Guid("c8c2fec0-924e-42cf-95e1-5a56c74566ac")
                        },
                        new
                        {
                            RoomImagePath = "505.jpg",
                            RoomId = new Guid("a1210a7c-a138-4e72-bdbc-9eaaffd11192")
                        });
                });

            modelBuilder.Entity("RoomApi.Domain.Entities.RoomType", b =>
                {
                    b.Property<Guid>("RoomTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("RoomTypeDesc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RoomTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoomTypeId");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            RoomTypeId = new Guid("9115f1c9-5d04-4199-9ba1-b507d5b14866"),
                            IsVisible = true,
                            RoomTypeDesc = "Phòng cơ bản cho thú cưng nhỏ",
                            RoomTypeName = "Phòng Tiêu Chuẩn"
                        },
                        new
                        {
                            RoomTypeId = new Guid("25f4b852-e34e-435d-88f9-7207e8d00149"),
                            IsVisible = true,
                            RoomTypeDesc = "Phòng rộng rãi, tiện nghi cao cấp",
                            RoomTypeName = "Phòng VIP"
                        },
                        new
                        {
                            RoomTypeId = new Guid("0c391bbe-fff6-4578-ba12-ab3497927553"),
                            IsVisible = true,
                            RoomTypeDesc = "Dành cho nhiều thú cưng cùng ở",
                            RoomTypeName = "Phòng Gia Đình"
                        });
                });

            modelBuilder.Entity("RoomApi.Domain.Entities.AgreeableBreed", b =>
                {
                    b.HasOne("RoomApi.Domain.Entities.Room", "Room")
                        .WithMany("AgreeableBreeds")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("RoomApi.Domain.Entities.Room", b =>
                {
                    b.HasOne("RoomApi.Domain.Entities.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("RoomApi.Domain.Entities.RoomAccessory", b =>
                {
                    b.HasOne("RoomApi.Domain.Entities.RoomType", "RoomType")
                        .WithMany("RoomAccessories")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("RoomApi.Domain.Entities.RoomImage", b =>
                {
                    b.HasOne("RoomApi.Domain.Entities.Room", null)
                        .WithMany("RoomImages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoomApi.Domain.Entities.Room", b =>
                {
                    b.Navigation("AgreeableBreeds");

                    b.Navigation("RoomImages");
                });

            modelBuilder.Entity("RoomApi.Domain.Entities.RoomType", b =>
                {
                    b.Navigation("RoomAccessories");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
